name: Public Credential Registry

on: [push]

jobs:
  create_registry_issuer:
    concurrency: create_registry_issuer
    name: Create Registry Issuer
    runs-on: ubuntu-latest
    steps:
      - name: checking out repo
        uses: actions/checkout@v2

      - name: Create Issuer
        id: create_issuer
        uses: transmute-industries/verifiable-actions@v0.0.11
        with:
          resource: "did"
          action: "generate"
          username: "transmute-industries"
          repository: "public-credential-registry-template"
          mnemonic: "${{ secrets.MNEMONIC }}"
          hd-path: "m/44'/0'/0'/0/0"
          key-type: "ed25519"
          file-output: "./issuers/did.json"

      - name: View Registry Issuer
        run: cat "./issuers/did.json"

  create_registry_credential:
    concurrency: create_registry_credential
    name: Create Registry Credential
    runs-on: ubuntu-latest
    steps:
      - name: checking out repo
        uses: actions/checkout@v2

      - name: Create a Verifiable Credential
        id: create_registry_credential
        uses: transmute-industries/verifiable-actions@v0.0.11
        with:
          resource: "credential"
          action: "create"
          username: "transmute-industries"
          repository: "public-credential-registry-template"
          mnemonic: "${{ secrets.MNEMONIC }}"
          hd-path: "m/44'/0'/0'/0/0"
          key-type: "ed25519"

          file-input: "./templates/example.json"
          file-output: "./credentials"

      - name: View Registry Index
        run: cat "./credentials/index.json"

      - uses: actions/cache@v2
        id: cache-save
        with:
          path: |
            ./*
          key: ${{ github.sha }}

  publish_registry:
    name: Publish Registry
    needs:
      - create_registry_credential
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - uses: actions/cache@v2
        id: cache-load
        with:
          path: |
            ./*
          key: ${{ github.sha }}

      - name: Deploy Registry
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
