name: Publish Credentials

on:
  # push:
  #   branches:
  #     - main
  # schedule:
  #   # Every day at midnight
  #   - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  publish_credentials:
    name: Publish Credentials
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create a Verifiable Credential
        id: create_registry_credential
        uses: transmute-industries/verifiable-actions@v0.0.11
        with:
          resource: "credential"
          action: "create"
          username: "transmute-industries"
          repository: "public-credential-registry-template"
          mnemonic: "${{ secrets.MNEMONIC }}"
          hd-path: "m/44'/0'/0'/0/0"
          key-type: "ed25519"

          file-input: "./templates/example.json"
          file-output: "./credentials"

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: main
          commit_message: Credentials updated

      - name: Publish Registry
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          enable_jekyll: true
          publish_dir: .
          exclude_assets: ".github"
