name: Publish Container

on:
  push:
    branches:
      - main
  # schedule:
  #   # Every day at midnight
  #   - cron: "0 0 * * *"
  # workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build_image:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Save Revision Metadata
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "./templates/opencontainers-meta.json"
          json: "${{steps.meta.outputs.json }}"

      - name: Convert Revision Metadata to Credential Template
        run: |-
          cat ./templates/container.json | jq ".credentialSubject=$(cat ./templates/opencontainers-meta.json)" > ./templates/container-template.json

      - name: Create a Verifiable Credential
        id: create_registry_credential
        uses: transmute-industries/verifiable-actions@v0.0.15
        with:
          resource: "credential"
          action: "create"
          username: "transmute-industries"
          repository: "public-credential-registry-template"
          mnemonic: "${{ secrets.MNEMONIC }}"
          hd-path: "m/44'/0'/0'/0/0"
          key-type: "ed25519"
          vc-format: "vc-jwt"
          file-input: "./templates/container-template.json"
          file-output: "./credentials/container-credential-example.json"

      - name: Clean up credential template
        run: |-
          rm ./templates/opencontainers-meta.json
          rm ./templates/container-template.json

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: main
          commit_message: Credentials updated

      - name: Publish Registry
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          enable_jekyll: true
          publish_dir: .
          exclude_assets: ".github"

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: |-
            ${{ steps.meta.outputs.labels }}
            org.opencontainers.image.vc=${{ fromJson(steps.create_registry_credential.outputs.response).data }}
